# Generated by Django 4.1 on 2022-10-28 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=500)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.CharField(blank=True, max_length=250, null=True)),
                ('title_mision', models.CharField(max_length=50)),
                ('mision', models.CharField(max_length=250)),
                ('title_vision', models.CharField(max_length=50)),
                ('vision', models.CharField(max_length=259)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='img/img4.jpg', upload_to='img/comments')),
                ('nombre', models.CharField(max_length=150)),
                ('posicion', models.CharField(help_text='Da una descripcion pequeña de lo que haces', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(default='agenciauncuarto@gmail.com', max_length=250, validators=[django.core.validators.EmailValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='img/img7.webp', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('logo', models.ImageField(default='img/logo.png', upload_to='img')),
                ('background_image', models.ImageField(default='img/img7.webp', upload_to='img')),
                ('background_video', models.FileField(blank=True, default='vid/reel_un_cuarto.mp4', help_text='solo vidoes mp4', upload_to='vid')),
            ],
        ),
        migrations.CreateModel(
            name='MetaElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('description_site', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=50)),
                ('spotimage', models.ImageField(upload_to='img/')),
                ('keywords', models.CharField(blank=True, max_length=150, null=True)),
                ('copyright_site', models.CharField(max_length=150)),
                ('copyright_url', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
                ('canonnical_link', models.CharField(blank=True, max_length=205)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('thumbnails', models.ImageField(blank=True, default='img/img4.jpg', upload_to='img/portfolio')),
                ('video', models.URLField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='PortafolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.URLField()),
                ('background_image', models.ImageField(default='img/img7.webp', upload_to='img/showreel')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=150)),
                ('facebook', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
                ('twiter', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
                ('instagram', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
                ('twich', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
                ('youtube', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
                ('linkedin', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnails', models.ImageField(default='img/img4.jpg', upload_to='img/team')),
                ('name', models.CharField(max_length=50)),
                ('possition', models.CharField(max_length=50)),
                ('facebook', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
                ('twiter', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
                ('instagram', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
                ('linkedin', models.URLField(blank=True, max_length=205, null=True, validators=[django.core.validators.URLValidator])),
            ],
        ),
    ]
