# Generated by Django 4.1 on 2022-11-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_cuarto', '0002_aboutussection_thumbnails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
