# Generated by Django 4.1 on 2022-11-07 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_cuarto', '0003_teamsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='foto',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='webuncuarto@gmail.com', max_length=250, validators=[django.core.validators.EmailValidator]),
        ),
    ]
